import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/app/ui/globals.css";
const inter = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className + " bg-gray-950 text-white"}>
        <div className="flex flex-col p-4 bg-zinc-900">
          <div className="flex gap-2 items-center">
            <span className="text-2xl text-primary">Crypton</span>
          </div>
          <span className="font-normal text-gray-500 text-sm">
            General info about more than 10000 cryptocurrencies.
          </span>
        </div>

        {children}
      </body>
    </html>
  );
}
