import type { Metadata } from "next";
import { Poppins } from "next/font/google";

import "@/app/ui/globals.css";
import Header from "./ui/Header";

const inter = Poppins({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className + " bg-gray-950 text-white"}>
        <Header />
        {children}
      </body>
    </html>
  );
}
